arpobserver-checkd(8)
=====================
:doctype: manpage


== NAME
arpobserver-checkd - check Ethernet/IP pairings for notable changes


[[synopsis]]
== SYNOPSIS
*arpobserver-checkd* ['OPTIONS']


[[description]]
== DESCRIPTION
*arpobserver-checkd* listens to Ethernet/IP pairings events from *arpobserverd*(8) and checks for notable changes.
It will alert about IP changes for the same MAC address and vice versa.
Pairings will be forgotton after not seen for a lease time of 1 day.


[[options]]
== OPTIONS
*-c*, *--config* 'file'::
    Read the configuration from 'file'.

*-h*, --help*::
    Show command line arguments and exit.

*-s*, *--state-file* 'file'::
    Use 'file' as state file to save pairings.
    The state file will be written all 5 minutes and on exit.
    By default the state file is located at '/var/lib/arpobserver/check.state'.

*--syslog*::
    Log program messages to syslog (daemon facility).
    By default messages are written to *stderr*.

*-v*, *--verbose*::
    Enable verbose output.

*-V*, *--version*::
    Show version information and exit.


[[configuration]]
== CONFIGURATION
The configuration file consists of key-value pairs, separated by a '=' sign. +
Lines starting with a '#' are ignored.

*LeaseTime*::
    Time in days for IP addresses to be leased. +
    Ethernet/IP pairing changes of an address last used before more than this time are not considered extraordinary. +
    The default is 1 day.

*LeaseRememberFactor*::
    Time in multiple of *LeaseTime* to rember addresses. +
    Currently unused Ethernet/IP pairings are rembered for this amount of time to report previous usage hints. +
    The default is 5 times the *LeaseTime*.

*ProtectIP*::
    IP address to protect. +
    The first encountered Ethernet/IP pairing matching this IP address will determine the Ethernet address of this protect entry. +
    See <<PROTECT>> section for more details.

*ProtectMAC*::
    Ethernet address to protect. +
    The first encountered Ethernet/IP pairing matching this Ethernet address will determine the Ethernet address of this protect entry. +
    See <<PROTECT>> section for more details.

*ProtectMACIPPairing*::
    Ethernet/IP address pair in the format: ethernet-address@ip-address +
    See <<PROTECT>> section for more details.

*ShmLogName*::
    Filename of the shared memory log name. +
    The default is '/arpobserver-shm-log'.

*StateSyncInterval*::
    Time interval to save the state to disk. +
    The default is 5 minutes. +
    Set to 0 to disable.


[[protect]]
== PROTECT
Protected entries are Ethernet/IP address pairings, which must not change.
Any discovered Ethernet/IP address pairing that does only match partially is reported.


== NOTES
To be able to read the shared memory object of *arpobserverd*(8), *arpobserver-check* should be started as the same user *arpobserverd* switches to.


[[see-also]]
== SEE ALSO
*arpobserverd*(8)


include::footer.adoc.template[]
