#!/bin/sh

set -eu

case "$1" in
  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

  purge)
    rm -Rf /var/lib/arpobserver
    userdel arpobserver || true
    ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
esac

#DEBHELPER#
